<?php

/**
 * Implements hook_theme for blocks.
 *
 *{@inheritDoc}
 */
function star_wars_api_theme($existing, $type, $theme, $path)
{ //unique, replaces the word "hook" must end in _theme
  return [
    'star_wars_api_block' => [ //should be unique, linked to build function in .php block plugin 
      'template' => 'starwars_api', //this is what points to the .html.twig file
      'variables' => [
        'welcome_message' => NULL,
      ],
    ],
  ];
}